export const actionType = {
  SET_GAME_MATRIX: 'SET_GAME_MATRIX',
  UPDATE_OPENED_CARDS: 'UPDATE_OPENED_CARDS',
  CLOSE_IMAGE_WITH_INDEX: 'CLOSE_IMAGE_WITH_INDEX',
  RESET_STATE: 'RESET_STATE',
  GAME_OVER: 'GAME_OVER',
  SET_GAME_DIFFICULTY: 'SET_GAME_DIFFICULTY',
  SET_MATRIX_DIMENSION: 'SET_MATRIX_DIMENSION',
};
